USE [master]
GO

/****** Object:  Database [outpostwars]    Script Date: 5/19/2018 9:43:16 PM ******/
DROP DATABASE [outpostwars]
GO

/****** Object:  Database [outpostwars]    Script Date: 5/19/2018 9:43:16 PM ******/
CREATE DATABASE [outpostwars]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'outpostwars', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\outpostwars.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'outpostwars_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\outpostwars_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [outpostwars] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [outpostwars].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [outpostwars] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [outpostwars] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [outpostwars] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [outpostwars] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [outpostwars] SET ARITHABORT OFF 
GO

ALTER DATABASE [outpostwars] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [outpostwars] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [outpostwars] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [outpostwars] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [outpostwars] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [outpostwars] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [outpostwars] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [outpostwars] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [outpostwars] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [outpostwars] SET  DISABLE_BROKER 
GO

ALTER DATABASE [outpostwars] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [outpostwars] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [outpostwars] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [outpostwars] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [outpostwars] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [outpostwars] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [outpostwars] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [outpostwars] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [outpostwars] SET  MULTI_USER 
GO

ALTER DATABASE [outpostwars] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [outpostwars] SET DB_CHAINING OFF 
GO

ALTER DATABASE [outpostwars] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [outpostwars] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [outpostwars] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [outpostwars] SET QUERY_STORE = OFF
GO

USE [outpostwars]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [outpostwars] SET  READ_WRITE 
GO

