//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllianceLedger
    {
        public int id { get; set; }
        public int playerID { get; set; }
        public System.DateTime timestamp { get; set; }
        public int resourceType { get; set; }
        public int value { get; set; }
        public int allianceID { get; set; }
        public int itemID { get; set; }
    
        public virtual Alliance Alliance { get; set; }
        public virtual Item Item { get; set; }
        public virtual Player Player { get; set; }
    }
}
