//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllianceMember
    {
        public int id { get; set; }
        public int idPlayer { get; set; }
        public int idAlliance { get; set; }
        public int rank { get; set; }
        public System.DateTime timestampJoin { get; set; }
        public int currency { get; set; }
    
        public virtual Alliance Alliance { get; set; }
        public virtual Player Player { get; set; }
    }
}
