//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alliance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alliance()
        {
            this.AllianceLedgers = new HashSet<AllianceLedger>();
            this.AllianceMembers = new HashSet<AllianceMember>();
            this.AllianceStores = new HashSet<AllianceStore>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int icon { get; set; }
        public int banner { get; set; }
        public string rank1title { get; set; }
        public string rank2title { get; set; }
        public string rank3title { get; set; }
        public string rank4title { get; set; }
        public string rank5title { get; set; }
        public int permInviteMembers { get; set; }
        public int permRemoveMembers { get; set; }
        public int permPromoteMember { get; set; }
        public int permKickMember { get; set; }
        public int permEditClan { get; set; }
        public int permEditPerms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllianceLedger> AllianceLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllianceMember> AllianceMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllianceStore> AllianceStores { get; set; }
        public virtual AllianceWallet AllianceWallet { get; set; }
    }
}
