//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BattleEvent()
        {
            this.ShipsLostLineItems = new HashSet<ShipsLostLineItem>();
            this.ShipsRemainingLineItems = new HashSet<ShipsRemainingLineItem>();
        }
    
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public int attackerID { get; set; }
        public int defenderID { get; set; }
        public int mapX { get; set; }
        public int mapY { get; set; }
        public int sectorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipsLostLineItem> ShipsLostLineItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipsRemainingLineItem> ShipsRemainingLineItems { get; set; }
    }
}
