//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fleet
    {
        public int id { get; set; }
        public int playerID { get; set; }
        public int shipID { get; set; }
        public int qty { get; set; }
        public bool showOnWorldMap { get; set; }
        public int mapX { get; set; }
        public int mapY { get; set; }
        public int sectorID { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
