//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSetting
    {
        public int hashExpirationHours { get; set; }
        public decimal baseMovementSpeed { get; set; }
        public bool alllowLogins { get; set; }
        public bool maintnenceMode { get; set; }
    }
}
