//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int id { get; set; }
        public Nullable<int> itemID { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> playerID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Player Player { get; set; }
    }
}
