//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long id { get; set; }
        public int playerID { get; set; }
        public string action { get; set; }
        public string details { get; set; }
        public System.DateTime timestamp { get; set; }
        public bool isCritical { get; set; }
        public bool isWarning { get; set; }
    }
}
