//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public int player1ID { get; set; }
        public int player2ID { get; set; }
        public int allianceID { get; set; }
        public string contents { get; set; }
        public bool isPlayerToPlayer { get; set; }
        public bool isToClan { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<bool> isRead { get; set; }
    }
}
