//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public int id { get; set; }
        public int mapX { get; set; }
        public int mapY { get; set; }
        public int sectorID { get; set; }
        public int resourceTypeID { get; set; }
        public int unitsReamining { get; set; }
    
        public virtual ResourceType ResourceType { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
