//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.AllianceLedgers = new HashSet<AllianceLedger>();
            this.AllianceMembers = new HashSet<AllianceMember>();
            this.FleetBuildings = new HashSet<FleetBuilding>();
            this.Fleets = new HashSet<Fleet>();
            this.Inventories = new HashSet<Inventory>();
            this.Logins = new HashSet<Login>();
            this.PlayerBuffs = new HashSet<PlayerBuff>();
            this.PlayerResources = new HashSet<PlayerResource>();
            this.ResearchCompleteds = new HashSet<ResearchCompleted>();
        }
    
        public int id { get; set; }
        public string characterName { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string passwordResetHash { get; set; }
        public Nullable<System.DateTime> passwordHashExpiration { get; set; }
        public string facebookToken { get; set; }
        public string googleToken { get; set; }
        public System.DateTime createdAtTimestamp { get; set; }
        public System.DateTime updatedAtTimestamp { get; set; }
        public System.DateTime lastLoginTimestamp { get; set; }
        public Nullable<bool> enabled { get; set; }
        public int allianceID { get; set; }
        public string sourceClickID { get; set; }
        public string sourceSub1 { get; set; }
        public string sourceSub2 { get; set; }
        public string sourceSub3 { get; set; }
        public string sourceSub4 { get; set; }
        public string sourceSub5 { get; set; }
        public bool firstLoginComplete { get; set; }
        public int sectorID { get; set; }
        public bool canLoginDuringMaintnence { get; set; }
        public string CLSID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllianceLedger> AllianceLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllianceMember> AllianceMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FleetBuilding> FleetBuildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fleet> Fleets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
        public virtual Outpost Outpost { get; set; }
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerBuff> PlayerBuffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerResource> PlayerResources { get; set; }
        public virtual PlayerSetting PlayerSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchCompleted> ResearchCompleteds { get; set; }
    }
}
