//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSetting
    {
        public int idPlayer { get; set; }
        public bool sendEmails { get; set; }
        public bool sendPush { get; set; }
        public bool sendBrowserPush { get; set; }
        public bool alertOnBuildComplete { get; set; }
        public bool alertOnBeingAttacked { get; set; }
        public bool alertOnAttack { get; set; }
        public bool musicEnabled { get; set; }
        public bool soundEffectsEnabled { get; set; }
        public bool tutorialEnabled { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
