//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerBuff
    {
        public int id { get; set; }
        public int IdPlayer { get; set; }
        public int statID { get; set; }
        public int value { get; set; }
        public int countdownRemaining { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual StatType StatType { get; set; }
    }
}
