//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchTree
    {
        public int id { get; set; }
        public int researchTreeParentID { get; set; }
        public int researchTreeChild1ID { get; set; }
        public int researchTreeChild2ID { get; set; }
        public int researchTreeChild3ID { get; set; }
    }
}
