//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectorMap
    {
        public int id { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public string objectType { get; set; }
        public Nullable<int> objectID { get; set; }
        public Nullable<int> sectorID { get; set; }
    
        public virtual Sector Sector { get; set; }
    }
}
