//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outpostwarsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatType()
        {
            this.PlayerBuffs = new HashSet<PlayerBuff>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool visibleToPlayer { get; set; }
        public bool forFleet { get; set; }
        public bool forOutpost { get; set; }
        public Nullable<int> typeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerBuff> PlayerBuffs { get; set; }
    }
}
